c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.17"

cmake_version:
  - ">=3.26.4,!=3.30.0"

glog_version:
  - ">=0.6.0"

h5py_version:
  - ">=3.8.0"

nlohmann_json_version:
  - ">=3.11.2"

spdlog_version:
  - ">=1.12.0,<1.13"

fmt_version:
  - ">=10.1.1,<11"
